# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04e5dfb4c9dc78a5dda17b7741cc5a9821bfa060593ca9cb43332b4c3db0e1c12d27959d43854b15777fe8d78c5a02d9764b2d3571575adc10d4fe5f14d172bf

test:
  secret_key_base: ec36bf86dd313f54c3f3727065cc072455731b3017ed4cd1f1454857f85ee627f5c3404453319802bccd4fa6586bed75cb0f46845c169e723e69c766ea8a0f2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
